### ISSUE TITLE
Use lightbox with Nuxt.js

### ISSUE THREAD

**Issue by gyxoBka** [pexea12/vue-image-lightbox#103]
HI, help me, please,  when i used lightbox without nuxt it worked perfectly, but i moved project to SSR Nuxt.js and i cant turn in on.
package.json
![Screenshot_3](https://user-images.githubusercontent.com/69042059/91883887-c6519280-ec8d-11ea-8771-6991238bbcf5.jpg)

added lazyload as nuxt plugin and have that error:
![Screenshot_4](https://user-images.githubusercontent.com/69042059/91884059-09ac0100-ec8e-11ea-9861-77f6a2a2a556.jpg)

**Comment by gyxoBka** [comment]
I tried that [solve](https://github.com/pexea12/vue-image-lightbox/issues/31#issuecomment-465499553) and it works nice. Is it right way to fix issue?

**Comment by pexea12** [comment]
Yes, it is. Basically I think the lightbox should only be rendered on the client side. It is not necessary to render it on the server side.
