### ISSUE TITLE
Clicking on the image causes the entire parent element to turn into a black screen.

### ISSUE THREAD

**Issue by secmin** [pexea12/vue-image-lightbox#106]
chrome: latest
lightbox: latest
nuxt.js: latest

If you use the development tool to shrink the image to the size of your phone and click on the image, it works fine. (The problem of moving to the top of the site when you close the image is probably due to the fact that it's fixed to the parent element this time.)
On the desktop, only the parent element goes to the black screen, and pressing the black screen takes you to the site top.
The image will be displayed without any problem until you press the image.
The vuetify v-dialog that I use in the same component shows the overlay all over the monitor screen without any problems.
What is the solution?

**Comment by imcvampire** [comment]
Could you provide a minimal reproduce process?

**Comment by secmin** [comment]
Here's how it works.
As an additional note, if the parent element is black, scrolling is not possible. Since the parent element is long and vertical, I think only the parent element is overlaid and the image is displayed in the center of the vertical parent element (probably). Since it can't be scrolled, the image seems to be hidden at the bottom, leaving a blackened parent element.
I haven't edited the css in this file.

<template>
  <div v-if="~">
      <v-row>
        <v-col v-for="(path, i) in media" :key="i">
          <v-img
            :src="path"
            @click="openGallery(i)"
          />
        </v-col>
      </v-row>
    <LightBox
      ref="lightbox"
      :media="media"
      show-light-box="false"
      disable-scroll="false"
    />
  </div>
</template>

<script>
methods: {
    openGallery(i) {
      this.$refs.lightbox.showImage(i)
    }
  }
</script>

**Comment by secmin** [comment]
There was an overlay on the parent element, but we solved it by changing the implementation.
