### ISSUE TITLE
Why remove slot footer when "media.length = 1"?

### ISSUE THREAD

**Issue by dinlyhor** [pexea12/vue-image-lightbox#108]
In my case, I want to use a slot footer even it media length = 1
why need to remove it when length = 1? 

example code:
<div  v-if="media.length > 1" class="vue-lb-footer-count">----</div>

**Comment by imcvampire** [comment]
Feel free to contribute to our project. Currently, hiding footer when there is only 1 image is 1 of our use case

**Comment by dinlyhor** [comment]
@imcvampire so can you show footer when the image is 1?

**Comment by imcvampire** [comment]
@dinlyhor No with the current code base.

**Comment by janosrusiczki** [comment]
IMHO the best would be to pass in a prop `alwaysShowFooter` which would default to false.
