### ISSUE TITLE
Next/Prev buttons don't work when initialized with an empty array

### ISSUE THREAD

**Issue by vietquocnguyen** [pexea12/vue-image-lightbox#14]
If you initialize the lightbox `<lightbox :images="imgs"></lightbox> `where imgs = []
Then later you populate it, lets say via ajax. Then you do `this.$refs.lightbox.showImage(0)`. It works, but breaks when you press the next / previous buttons.

**Comment by vietquocnguyen** [comment]
I fixed this, with <lightbox v-if="imgs.length" :images="imgs"></lightbox>

**Comment by pexea12** [comment]
Yeah, sure. You'd better go with `<lightbox v-if="imgs.length" :images="imgs"></lightbox>` instead of modifying the lightbox.
