### ISSUE TITLE
Can you show the demo source code

### ISSUE THREAD

**Issue by liujingjing5** [pexea12/vue-image-lightbox#20]
The effect is so good， but in my project has some  problem,
I don`t know why
Can you show the demo source code

think u~

**Comment by pexea12** [comment]
The demo source code is in the `src` folder (https://github.com/pexea12/vue-image-lightbox/tree/master/src). You can also look into `App.vue` (https://github.com/pexea12/vue-image-lightbox/blob/master/src/App.vue)

**Comment by liujingjing5** [comment]
O(∩_∩)O  think u
