### ISSUE TITLE
Main image doesn't have `siteLoading`

### ISSUE THREAD

**Issue by iam-raihan** [pexea12/vue-image-lightbox#27]
siteLoading works for thumbles but not for main image.

**Comment by imcvampire** [comment]
Currently, the main image doesn't support `siteLoading`

**Comment by iam-raihan** [comment]
may i know why only for thumbles?

**Comment by imcvampire** [comment]
If I remember correctly, there is a bug when implementing this feature for the main image. @pexea12, can you confirm it?

**Comment by pexea12** [comment]
Because using `v-lazy` with main image creates an ugly display when switching images. 

![image](https://user-images.githubusercontent.com/10600525/41548625-b6654116-734d-11e8-90fa-1d383d3fb46d.png)

Therefore, I decide not to use `v-lazy` in this situation.

**Comment by arturaum** [comment]
I change "siteloading.gif" to another transparent .gif  file фnd it started to show up pretty well for main image.
Currently I use [this image](https://novosibirsk.incom-auto.ru/images/basicloader.gif).
