### ISSUE TITLE
SSR options

### ISSUE THREAD

**Issue by Markvandersteen** [pexea12/vue-image-lightbox#31]
Hello thanks for the package, already using it in one of my projects. 
I do have a question however. 

Is there a way to use this package with ssr/nuxt? 
If so it would be awesome if the readme contained an example, if not is something that is going to be added?

**Comment by imcvampire** [comment]
Hi @Markvandersteen,

I use this package with SSR and it works perfectly! What problem do you face now?

**Comment by Markvandersteen** [comment]
At the moment i'm getting some window not defined errors.

**Comment by Markvandersteen** [comment]
I got it working, i did need some extra code some make it work with nuxtjs.

**Comment by dmiotti** [comment]
Hi, @Markvandersteen what is the extra code you've added in order to get it work.

**Comment by lexcode** [comment]
Hey @Markvandersteen I am getting the same issue, could you paste your extra code solution in nuxt please?

**Comment by lexcode** [comment]
I found it, 
### plugins/lightbox.js
```js
if (process.BROWSER_BUILD) {
  const VueTouch = require('vue-touch')
  Vue.use(VueTouch, { name: 'v-touch' })
}
```
```js
build: {
    vendor: ['vue-touch'],
}
```

**Comment by Markvandersteen** [comment]
@dmiotti @lexcode My approach was to use the System.import function. 
When the component is mounted. I import the things I need.
```

 async loadLightBox() {
        Promise.all([
          System.import('vue-touch'),
          System.import('vue-lazyload'),
          System.import('vue-image-lightbox')
        ]).then((modules) => {
          const VueTouch = modules.shift(),
            VueLazyLoad = modules.shift(),
            LightBox = modules.shift();


          Vue.use(VueTouch, {name: 'v-touch'});
          Vue.use(VueLazyLoad);
          Vue.component('lightbox', LightBox);
          this.lightboxReady = true;
        });
      },
    },
    async mounted() {
      this.loadLightBox();
    }
`

**Comment by sven-ra** [comment]
An easy way to use it in Nuxt is like this:

Make a plugin file: 
`import Vue from 'vue'
import VueLazyLoad from 'vue-lazyload'
import VueTouch from 'vue-touch'
import LightBox from 'vue-image-lightbox'
require('vue-image-lightbox/dist/vue-image-lightbox.min.css')

Vue.use(VueTouch, { name: 'v-touch' })
Vue.use(VueLazyLoad)
Vue.component('light-box', LightBox)
`

Add the plugin to nuxt.config with SSR disabled:
`plugins: [
    {
      src: '~/plugins/vue-lightbox-pluign.js',
      ssr: false
    }
  ]`

**Comment by anaethoss** [comment]
@sven-ra I have faced the same issue with nuxt then i have followed your solution but a little bit modified with ```<no-ssr>``` tag instead of ```this.isMounted``` and it worked for me :)
