### ISSUE TITLE
.vue-lb-container  z-index value is different between dev and build

### ISSUE THREAD

**Issue by mliBoy** [pexea12/vue-image-lightbox#34]
When I use npm install the plugin, I find .vue-lb-container 'z-index' is  1, because it is 1 in dist/vue-image-lightbox.min.css,  but it is 2001 in your src/components/style.css,  I wish your guys can fix it.

**Comment by pexea12** [comment]
I changed `OptimizeCSSPlugin` options so that `z-index` is not changed after building. This error is fixed in version 6.0.0

**Comment by pexea12** [comment]
https://github.com/pexea12/vue-image-lightbox/pull/41
