### ISSUE TITLE
缩略图不显示, z-index 有问题

### ISSUE THREAD

**Issue by nfwyst** [pexea12/vue-image-lightbox#38]
按照api设定了 thumb 与 src 但是 thumb 渲染的时候没有图片内容
<img width="711" alt="2018-05-31 12 18 14" src="https://user-images.githubusercontent.com/35720450/40761121-bc4e6e5c-64cc-11e8-82f7-d4f599e4c4e1.png">

**Comment by imcvampire** [comment]
Hi, I think you can customize `z-index` by yourself if you use a higher `z-index` in your website
