### ISSUE TITLE
The thumbnails are not displayed

### ISSUE THREAD

**Issue by nfwyst** [pexea12/vue-image-lightbox#39]
I set images according to the start guide, but the thumbnails image is empty, can you help me ?

**Comment by nfwyst** [comment]
and can I have any @close method to hold the images when i close lightbox ?

**Comment by nfwyst** [comment]
its like this 
```javascript
<lightbox :images="images" @close="refresh"></lightbox>
```
thanks!

**Comment by imcvampire** [comment]
Can you share some reproduction code?

**Comment by nfwyst** [comment]
ok, no problem now.
