### ISSUE TITLE
Lightbox thumbnails not displaying at all

### ISSUE THREAD

**Issue by hannerr** [pexea12/vue-image-lightbox#47]
I´ve implemented the lightbox and everything is working fine, except the thumbnails in the Lightbox don´t load....is this a known issue?
tx hanna

**Comment by imcvampire** [comment]
Hi,

Can you provide a simple reproduction?

**Comment by hannerr** [comment]
<template>
  <div class="container">
      <div class="row">
        <div class="col-7">
            <img @click="openGallery" :src="`/static/${images[0].pfad}`" width="100%" alt="`${images[0].title}`">
            <LightBox :images="imagesForLightbox"
              ref="mylightbox"
              :show-caption="true"
              :show-light-box="false"
              :show-thumbs="true"
            ></LightBox>
        </div>
        </div>
      </div>
</template>

<script>
  import LightBox from 'vue-image-lightbox'
  import { mapState } from 'vuex'

  export default {
    data(){     
    },
    components:{ LightBox },
    computed:{
      images(){
        return this.objectdetails.bilder ? this.objectdetails.bilder : [];
      },
      imagesForLightbox() {
        return this.images.map( i => {
          return {
            src : '/static/' + i.pfad,
            thumb : '/static/' + i.pfad,
            caption: i.titel
          }
        })
      },
    methods: {
      openGallery() {
        this.$refs.mylightbox.showImage(0)
      }
    }
  }
</script>
This would be the simplified code.
I also attach a screenshot
![unbenannt](https://user-images.githubusercontent.com/26022847/46460142-601b1700-c7bb-11e8-9b1a-dd9c75905ab4.PNG)

I hope this helps, I would really need help ;-)
ty hanna

**Comment by pexea12** [comment]
Can I see your image url? It would be even better if you give me some of your original images. You can upload to https://imgur.com/

**Comment by hannerr** [comment]
Unfortuneately I am ona dev environment so i cant share the url, does a screenshot of the devtools source help? Here you can see that the vue-lb-modal-thumbnail is not filled with data...I gues this should contain sthg?
![source](https://user-images.githubusercontent.com/26022847/46464050-ae351800-c7c5-11e8-857c-684b7c7758b1.PNG)

**Comment by kamontat** [comment]
Confirm.

**Comment by pexea12** [comment]
@kamontat Can you provide a sample of your code? Everything works fine in my environment

**Comment by pexea12** [comment]
Version 6.1.2 might solve your problem

https://github.com/pexea12/vue-image-lightbox/releases/tag/6.1.2

https://github.com/pexea12/vue-image-lightbox/issues/59
