### ISSUE TITLE
ES5 build

### ISSUE THREAD

**Issue by ondrej-janosik** [pexea12/vue-image-lightbox#48]
Hi,

can you adjust babel so this lib produces ES5 compatible build? This is a nice lib but cannot be used when an app needs to support IE11.

Thanks, Ondrej.

**Comment by imcvampire** [comment]
Hi @ondrej-janosik, it already produces ES5 build! What is your problem when use it on IE11?

**Comment by ondrej-janosik** [comment]
Are you sure? Because when I look into the distributed code, I can see object-shorthand, which is not supported by IE11.

![image](https://user-images.githubusercontent.com/18070427/46936620-338ab900-d05f-11e8-81ff-aa85c1619206.png)

**Comment by imcvampire** [comment]
Ah okay, thank you for the report! Let me see if I can do anything!

**Comment by imcvampire** [comment]
@ondrej-janosik I think you can create a PR anytime you like, you just have to fork this project and push your new to the new repo and create a PR from it to this repo

**Comment by sven-ra** [comment]
@ondrej-janosik Hello! How did you fix this locally?

**Comment by djvov** [comment]
>  I have already fixed this issue locally. @imcvampire

@ondrej-janosik Hello! How did you fix this?

**Comment by ondrej-janosik** [comment]
Hi guys, if you use https://cli.vuejs.org/, you can use https://cli.vuejs.org/config/#transpiledependencies option. By default, babel-loader ignores all files inside node_modules. If you want to explicitly transpile this dependency with Babel, you can list it in this option. Otherwise, you can fork this library and adjust the babel settings https://github.com/pexea12/vue-image-lightbox/blob/master/.babelrc

**Comment by djvov** [comment]
@ondrej-janosik 
> you can fork this library and adjust the babel settings
this works, thanks!

> If you want to explicitly transpile this dependency with Babel, you can list it in this option.
which dependency I should wrote in this list?
