### ISSUE TITLE
Failed to resolve directive: lazy

### ISSUE THREAD

**Issue by alexpetroni** [pexea12/vue-image-lightbox#5]
Even if I installed vue-lazyload this error appears. 
Thank you

**Comment by pexea12** [comment]
Can you give me more specific information? Your code, your log or a screenshot maybe. It could help me detect your problem.

**Comment by pexea12** [comment]
`vue-lazyload` is actually a dependency to my package. You don't need to install it if you only `vue-lazyload` for my package.

**Comment by alexpetroni** [comment]
It is needed to specify Vue.use(VueLazyload) in main.js to solve the problem. Probably it would help if you would give a full working example. Where should be css imported require('vue-image-lightbox/dist/vue-image-lightbox.min.css')? Thank you for your prompt support!

**Comment by pexea12** [comment]
Thank you, I will update the document.  
You can view this file to see how the package works. [App.vue](https://github.com/pexea12/vue-image-lightbox/blob/master/src/App.vue)

If you are using Webpack, you have to enable `css-loader` 
The CSS should be imported at your entry file (normally `main.js`)
```
require('vue-image-lightbox/dist/vue-image-lightbox.min.css')
```

**Comment by pexea12** [comment]
I have updated README. You should check it again.

**Comment by alexpetroni** [comment]
Thank you, it works! Grateful for this component!
