### ISSUE TITLE
Can't work in IE 

### ISSUE THREAD

**Issue by piange** [pexea12/vue-image-lightbox#50]
![image](https://user-images.githubusercontent.com/24648812/48113382-9bff3b80-e295-11e8-8c90-63441a74aba9.png)

**Throw SyntaxError: lack of ":", can't find the reason. help !!!**

**Comment by xrado** [comment]
I have same issue

**Comment by imcvampire** [comment]
Ref https://github.com/pexea12/vue-image-lightbox/issues/48
