### ISSUE TITLE
IE11 Issue

### ISSUE THREAD

**Issue by mjones2620** [pexea12/vue-image-lightbox#51]
Getting an error in IE11 Expected ':'

**Comment by nikitae** [comment]
Also having this issue in IE11:
Uncaught (in promise) SyntaxError: Expected ':'

Does anybody know a workaround for this ?

**Comment by chrismeyers** [comment]
Code in `node_modules` won't get transpiled unless added to [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies) in `vue.config.js`.  I wasn't able to get this plugin to work using `transpileDependencies`, but I ended up getting it to work by placing the code in my `components` directory.

**Comment by pexea12** [comment]
It seems that IE 11 needs `polyfill` to work with Vue. Check these links out:
https://stackoverflow.com/questions/52881807/compiling-es6-and-vue-js-not-working-in-ie-11
https://stackoverflow.com/questions/52056358/vue-cli-3-project-not-working-on-ie-11
