### ISSUE TITLE
More then one gallery on the same page?

### ISSUE THREAD

**Issue by egerb** [pexea12/vue-image-lightbox#53]
Can't figure out how to use your component if I need to show 2 more groups of images on the same page.
Thanx for any help

**Comment by pexea12** [comment]
You should change the `ref` key.

For example, you have 2 Lightbox A and Lightbox B


```
<LightBox 
        :images="imagesA" 
        ref="lightboxA"
        :show-light-box="false"
      ></LightBox>

<LightBox 
        :images="imagesB" 
        ref="lightboxB"
        :show-light-box="false"
      ></LightBox>
```

To open lightbox A, just do `this.$refs.lightboxA.showImage(0)`. Similarly, to open lightbox B, `this.$refs.lightboxB.showImage(0)`

**Comment by pexea12** [comment]
I see. In this case, it is unnecessary to add lightbox to every step of the loop. Instead of that, you should use only 1 instance of lightbox and change your code a little bit.

```
<div v-for="message, messageIndex in messages" :key="message.id">
   <b-card-body class="col-12 col-sm-8">
      <p class="card-text" v-html="message.content">
      </p>
      <em v-if="message.attachments.length > 0" slot="footer">
        <div class="row" >
          <b-img 
            v-for="(image, imageIndex) in pics[message.id]"  
            v-lazy="image.src" 
            @click="openGallery(messageIndex, imageIndex)" 
            :key="index"
          />
        </div>
      </em>
    </b-card>
  </b-card-body>

</div>

<LightBox v-if="messages[currentIndex].attachments.length > 0"
   :images="pics[messages[currentIndex].id]"
   :ref="lightbox"
   :show-caption="true"
   :show-light-box="false"
></LightBox>
```

The variable `currentIndex` is the index of `messages` that you select. Therefore, you should change your `openGallery` method a little bit:

```
data() {
  return {
    currentIndex: null,
  }
},

methods: {
  openGallery(messageIndex, imageIndex) {
    this.$set(this, 'currentIndex', messageIndex)
    ... // Your old method
  }
}
```

You would need to render only 1 instance of lightbox in this case and the rendering performance would be much better

**Comment by egerb** [comment]
Got it, let me try

**Comment by egerb** [comment]
Hmm, I 'v got weird situation, in openGallery:
`console.log(this.$refs);
 console.log(this.$refs.lightbox);`
shows:
`{}
lightbox: VueComponent {_uid: 25, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
__proto__: Object`
and 
`undefined`

**Comment by pexea12** [comment]
I think you should remove `v-if` in lightbox or change it to `v-show`

**Comment by egerb** [comment]
OMG, right,  thanx a lot, worked!

**Comment by pexea12** [comment]
No problem. I am not sure what the idea of `v-if` in this case. I think you should remove it because changing to `v-show` doesn't mean anything.

**Comment by egerb** [comment]
Let me explain: 
I 'v got list of messages, every message could have an attachments or not.
When I fetching messages from server  - I put all attachments to pics list : pics[message.id] = [array of objects for light box]
Then on click I need to activate your component and point images property to related pics[message.id].
And now I see errors in console...

**Comment by pexea12** [comment]
My code sample is just a demo. I think you should check the `currentIndex` more to make sure everything work. For example, you can change `currentIndex` to 0 at the beginning.

**Comment by egerb** [comment]
In my case I've used message Id as index and I've used v=if or v-show to activate component if I have attachments, because sometimes I haven't, and I don't want to initiate component.
