### ISSUE TITLE
Could you add onClose event?

### ISSUE THREAD

**Issue by focussing** [pexea12/vue-image-lightbox#62]
This event would fire when the lightbox is closed.

Are there examples of how to work with the events this module provides?
Thank you!

**Comment by tibormarias** [comment]
I would be grateful for an answer on that issue as well!

**Comment by LeXeL** [comment]
So to do a turn around for this You can specify a template inside the component in the close slot like this: 

```
<template v-slot:close>
    <div class="lightbox__close" @click="functionToCallOnClose()">
        <slot name="icon-close">&times;</slot>
      </div>
<template>
```

**Comment by pjvanwijk** [comment]
There is already an event that fires on close:
> onOpened(value): true to emit when the lightbox is opened and false when it is closed.

So you could do something like:
```
<LightBox
    @onOpened="onLightBoxToggle($event)"
    // other props>
</LightBox>
```
And then in your methods:
```
onLightBoxToggle: function(event) {
    if (!event) {
        // stuff to do when lightbox is closed
    } else {
        // stuff to do when lightbox is opened
    }
}
```
I hope this helps.

**Comment by mrinalini-m** [comment]
Added `onClosed` event with [this pull request](https://github.com/pexea12/vue-image-lightbox/pull/87).
