### ISSUE TITLE
Failed to mount component

### ISSUE THREAD

**Issue by freimaks** [pexea12/vue-image-lightbox#7]
After update vue-image-lightbox have error:
"[Vue warn]: Failed to mount component: template or render function not defined. 
(found in <Lightbox>)"
![image](https://cloud.githubusercontent.com/assets/26241659/26562349/431c3380-44ce-11e7-88e4-0761e923563c.png)

**Comment by schlaus** [comment]
Apparently the dist version is not built correctly.

**Workaround**
import the component like this:
`import Lightbox from 'vue-image-lightbox/src/components/Lightbox'`

**Comment by pexea12** [comment]
I have already fixed the production build in version 5.3.0. Thank you for your contribution!

**Comment by mmieluch** [comment]
Is it possible there's been a regression? I'm using version 6.0.1 and experiencing exactly the same behaviour.
