### ISSUE TITLE
Avoid flicker when loading full size images

### ISSUE THREAD

**Issue by janosrusiczki** [pexea12/vue-image-lightbox#77]
As opposed to the demo, on my site I'm using different files for thumbnails / full size images. When I open the lightbox or click the next image, for a moment all that's displayed is a little box on the middle of the screen (while the image loads). Is it possible to avoid this?

![lightbox](https://user-images.githubusercontent.com/189468/64203815-fd377180-ce9c-11e9-8a70-59bea8e29758.gif)

As you can see, after the images are loaded everything works fine.

**Comment by Skylercrane23** [comment]
Any updates to this?

**Comment by pexea12** [comment]
Not yet now, I am still working on it

**Comment by pexea12** [comment]
https://github.com/pexea12/vue-image-lightbox/releases/tag/7.1.3
