### ISSUE TITLE
Responsive Thumbnail Section?

### ISSUE THREAD

**Issue by Skylercrane23** [pexea12/vue-image-lightbox#79]
Is there a way the thumbnail section can be responsive? I have seen a few other lightbox examples where depending on the screen size the number of thumbnails changes. Is there a way to do that with this package? or is it something I need to add my own custom CSS/Vue computed property for the nThumbs?

Thanks!

**Comment by pexea12** [comment]
I think you can customize your images using CSS. The lightbox already have some CSS classes for you such as `vue-lb-thumbnail-wrapper`.
