### ISSUE TITLE
Onchange?

### ISSUE THREAD

**Issue by Nash54** [pexea12/vue-image-lightbox#80]
Is there any method to know when you change images?

**Comment by kitce** [comment]
I was looking for this too, and then I found the `onImageChanged` event, not documented, may break in future minor versions, use with caution.

You can use it to get the changed image index

```html
<light-box :media="media" @onImageChanged="handleImageChanged" />
```

```js
methods: {
  handleImageChanged (imageIndex) {
    // ...do something with imageIndex
  }
}
```

https://github.com/pexea12/vue-image-lightbox/blob/master/src/components/LightBox.vue#L311

**Comment by pexea12** [comment]
It's now in README.
