### ISSUE TITLE
Lazy Load Large (src) image Only when Gallery Opened / thumbs clicked?

### ISSUE THREAD

**Issue by khaughton** [pexea12/vue-image-lightbox#81]
I am using the example with lazy-load (.src) and then openGallery to get Lightbox to show.

Since a typical page may have 20 images or so, and, they could be large, I notice that its the large images (not the thumbs) that are put into the thumb (background on small divs) then when click, it starts lightbox at that image.  Which is great.  But is there any way to only have the thumbs lazy-loaded, then, when opening lightbox gallery, only then have the full size image lazy loaded, as it's possible not all visitors to the page will even want to click photos.  

Here is my code (so maybe it's just a simple adjustment you can recommend, or I've missed something likely, looks great by the way).

	<ul class="photoThumbs">
        <li class="thumb-li"
          v-for="(image, index) in images" >
          <div v-lazy:background-image="image.src"  :class="'lazy-thumb'" @click="openGallery(index)">
          </div>

Tried to go with ="image.thumb" but then open LightBox and only get a gallery of the small thumbs.  At 8,000 pages with 10 to 20 images per page, and heavy traffic, I'd prefer to download thumbs and only download the large image when someone clicks the thumb or moves to next image in the gallery.  Hopefullly I've just not missed something.

**Comment by jasonbronson** [comment]
@khaughton can you show what is in the openGallery() call?

**Comment by khaughton** [comment]
oh yes, forgot to include that thanks ...

		    openGallery(index) {
     			this.$refs.lightbox.showImage(index);
   			},

and again the block of code that has the lightbox (i fill .src, .thumb, caption);

<ul class="photoThumbs">
        <li class="thumb-li"
          v-for="(image, index) in images" >
          <div v-lazy:background-image="image.src" :class="'lazy-thumb'" @click="openGallery(index)">
          </div>
          <div v-if="admin" class="feature-link">
             <a :href="'/image/trail/feature/' + id + image.src.substr(image.src.lastIndexOf('/'))"><strong>feature</strong></a>
          </div>
        </li>
</ul>

  <LightBox 
		:images="photos"
		ref="lightbox"
                :show-caption="true"
                :show-light-box="false">
    </LightBox>

</div>
</template>

<script>    
   import LightBox from 'vue-image-lightbox';
    import prettyJSON from "../utilities/prettyJson.js";
    require('vue-image-lightbox/dist/vue-image-lightbox.min.css');

**Comment by khaughton** [comment]
... any opinions to lazy loading large images only on gallery open ...

**Comment by khaughton** [comment]
.. solved this with the following (used my own solution for thumb display) and only open lightbox if an image clicked, seems to only load thumbs until one is clicked.

<ul class="photoThumbs">
      <li class="thumb-li" v-for="(image, index) in images" >
          <div :class="'photo-thumb'" :style="{ backgroundImage: 'url(' + image.thumb + ')' }" 
          @click="openGallery(index)">
          </div>

.. and openGallery same as before (so I am just skipping the lazy load in the initial v-for).
