### ISSUE TITLE
closeLightBox methods

### ISSUE THREAD

**Issue by aimadghssisse** [pexea12/vue-image-lightbox#82]
hey,
am really like the package , just  need help how using method closeLightBox ?

`            <lightbox
                alt=""
                class="mw-100 w-auto"
                v-if="data.image"
                :images="[data.image.full]"
            ></lightbox>`

**Comment by pexea12** [comment]
You should add a `ref` to the lightbox:

```
<lightbox 
  class="mw-100 w-auto" 
  v-if="data.image" 
  :images="[data.image.full]" 
  ref="lightbox"
></lightbox>
```

then 
```
this.$refs.lightbox.closeLightBox();
```
