### ISSUE TITLE
Using footer slot removes image count box

### ISSUE THREAD

**Issue by titusdecali** [pexea12/vue-image-lightbox#83]
Is there a way to use the footer <slot> while also not disabling the image counter?

**Check gif below for issue:**
![image counter issue](https://user-images.githubusercontent.com/4532534/71707502-95366f00-2e2d-11ea-9007-ca274e04b7a7.gif)

**Comment by pexea12** [comment]
You need to implement your own counter. Note that the slot for footer:
```
                <slot
                  name="footer"
                  :current="select + 1"
                  :total="media.length"
                >
                  {{ select + 1 }} / {{ media.length }}
                </slot>

```

You can use `current` and `total` in your own footer.
