### ISSUE TITLE
showImage will scroll the page to the top

### ISSUE THREAD

**Issue by satbirdd** [pexea12/vue-image-lightbox#84]
showImage will scroll the view to the top of the page, but i want it to be the place as when i call it, how can i do that?

**Comment by tharwat997** [comment]
@satbirdd 

I had the same issue but then when I set `:disableScroll="false"` it worked fine.

**Comment by pexea12** [comment]
I don't have this issue:

![Uploading image.png…]()

Maybe you can provide a more detailed example.

**Comment by JulianMelzig** [comment]
@pexea12 I am experiencing the same issue

**Comment by pexea12** [comment]
@JulianMelzig Did you try the solution of @tharwat997 ?

**Comment by secmin** [comment]
I have the same problem.
Of course, the above setup did not improve the situation.
The structure of the component uses nuxt.js and writes directly to index.vue in the page directory.
Cause unknown.
Do you have a solution?
