### ISSUE TITLE
How to use the srcset?

### ISSUE THREAD

**Issue by Desory** [pexea12/vue-image-lightbox#89]
Hello, i've seen the demo but i cannot figure out how to use the srcset for different browser resolutions. Can you tell me more?
thanks,
@pexea12 
Desory

**Comment by Desory** [comment]
No answer provided. If i shall get to it and find out how to use it , ill post it here.

**Comment by imcvampire** [comment]
@Desory Please check the docs on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset

**Comment by janosrusiczki** [comment]
It's an HTML thing, there's a longer documentation [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images).
