### ISSUE TITLE
Multiple videos are not re-rendering the video component when switching between them

### ISSUE THREAD

**Issue by carlos-ribeiro-cedro** [pexea12/vue-image-lightbox#91]
Needs to add a KEY on the video tag as well as in the source.

<video
              v-else
              ref="video"
              **:key="media[select].sources[0].src"**
              controls
              :width="media[select].width"
              :height="media[select].height"
              :autoplay="media[select].autoplay"
            >

**Comment by pexea12** [comment]
https://github.com/pexea12/vue-image-lightbox/releases/tag/7.1.1
