### ISSUE TITLE
showImage flashes first image before showing desired image

### ISSUE THREAD

**Issue by danfwdmotion** [pexea12/vue-image-lightbox#96]
When using the showImage method when the lightbox is closed, the lightbox appears with the first image and THEN shows the correct image, whereas I would expect the lightbox to remain hidden until the correct image is ready to be displayed.

This occurs in all browsers, latest version of the package (7.1.0)

**Comment by janosrusiczki** [comment]
I brought this up earlier here: https://github.com/pexea12/vue-image-lightbox/issues/77

PS. It is fixed in my fork, take a look: https://github.com/haiafara/vue-it-bigger

**Comment by janosrusiczki** [comment]
The fix for this particular problem is here, if someone wants to backport it: https://github.com/haiafara/vue-it-bigger/commit/8f78a82128ab4600ddffa3e81235493b175e496c

**Comment by pexea12** [comment]
Thanks @janosrusiczki, I fixed it in https://github.com/pexea12/vue-image-lightbox/releases/tag/7.1.3

**Comment by danfwdmotion** [comment]
Thanks for the speedy resolve guys!
